=== inspirehep/author.xml/example-files/author.dtd
<!-- 
********************************************

  Collaboration Author Lists - author.dtd

********************************************
Date: August 2010
-->
<!ELEMENT collaborationauthorlist ( cal:creationDate, cal:publicationReference, cal:collaborations, cal:organizations, cal:authors ) >
<!ATTLIST collaborationauthorlist
	  xmlns:foaf CDATA #FIXED "http://xmlns.com/foaf/0.1/" 
	  xmlns:cal  CDATA #FIXED "http://inspirehep.net/info/HepNames/tools/authors_xml/"
>

<!ELEMENT cal:creationDate ( #PCDATA ) >
<!ELEMENT cal:publicationReference ( #PCDATA ) >

<!-- **************** COLLABORATIONS ********************* -->
<!ELEMENT cal:collaborations ( cal:collaboration+ ) >
    <!ELEMENT cal:collaboration ( foaf:name, cal:experimentNumber?, cal:group? ) >
    <!ATTLIST cal:collaboration 
	      id ID #REQUIRED 
    >

    <!ELEMENT cal:experimentNumber ( #PCDATA ) >

    <!ELEMENT cal:group ( #PCDATA ) >
    <!ATTLIST cal:group 
	      with IDREF #IMPLIED 
    >
<!-- ORGANIZATIONS -->
<!ELEMENT cal:organizations ( foaf:Organization+ ) >
    <!ELEMENT foaf:Organization ( cal:orgDomain?, foaf:name, cal:orgName*, cal:orgStatus*, cal:orgAddress?, cal:group? ) >
    <!ATTLIST foaf:Organization 
	      id ID #REQUIRED 
    >

    <!ELEMENT cal:orgAddress ( #PCDATA ) >
    <!ELEMENT cal:orgDomain ( #PCDATA ) >

    <!ELEMENT cal:orgName ( #PCDATA ) >
    <!ATTLIST cal:orgName 
	      source CDATA "INTERNAL" 
    >

    <!ELEMENT cal:orgStatus ( #PCDATA ) >
    <!ATTLIST cal:orgStatus 
	      collaborationid IDREF #IMPLIED 
    >

<!-- AUTHORS -->
<!ELEMENT cal:authors ( foaf:Person+ ) >
    <!ELEMENT foaf:Person ( foaf:name?, cal:authorNameNative?, foaf:givenName?, foaf:familyName, cal:authorSuffix?, cal:authorStatus?, cal:authorNamePaper, cal:authorNamePaperGiven?, cal:authorNamePaperFamily?, cal:authorCollaboration?, cal:authorAffiliations?, cal:authorids?, cal:authorFunding? ) >

    <!ELEMENT foaf:familyName ( #PCDATA ) >
    <!ELEMENT foaf:givenName ( #PCDATA ) >
    <!ELEMENT foaf:name ( #PCDATA ) >

    <!ELEMENT cal:authorNameNative ( #PCDATA ) >
    <!ELEMENT cal:authorNamePaper ( #PCDATA ) >
    <!ELEMENT cal:authorNamePaperGiven ( #PCDATA ) >
    <!ELEMENT cal:authorNamePaperFamily ( #PCDATA ) >
    <!ELEMENT cal:authorStatus ( #PCDATA ) >
    <!ELEMENT cal:authorSuffix ( #PCDATA ) >

    <!ELEMENT cal:authorCollaboration EMPTY >
    <!ATTLIST cal:authorCollaboration 
	      collaborationid IDREF "c1"
	      position CDATA #IMPLIED 
    >

    <!ELEMENT cal:authorAffiliations ( cal:authorAffiliation* ) >
    <!ELEMENT cal:authorAffiliation EMPTY >
    <!ATTLIST cal:authorAffiliation 
	      organizationid IDREF #REQUIRED 
	      connection CDATA "Affiliated with"
    >

    <!ELEMENT cal:authorids ( cal:authorid* ) >
    <!ELEMENT cal:authorid ( #PCDATA ) >
    <!ATTLIST cal:authorid 
	      source CDATA #REQUIRED 
    >
    <!ELEMENT cal:authorFunding ( #PCDATA ) >

=== inspirehep/author.xml/example-files/example-fulldata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE collaborationauthorlist SYSTEM "http://inspirehep.net/info/HepNames/tools/authors_xml/author.dtd">
<!-- 
	Example of an authors.xml file holding a full set of data.
	It includes examples for people with multiple affiliations and/or author IDs.
	It includes an example of institutes that represent an entity (a59a and a59b), but are 
	addressed independently hence an author might be affiliated to only one part.
!-->
<collaborationauthorlist 
   	xmlns:foaf="http://xmlns.com/foaf/0.1/" 
   	xmlns:cal="http://inspirehep.net/info/HepNames/tools/authors_xml/">
  
  <cal:creationDate>2010-05-12_10:10</cal:creationDate>
  <cal:publicationReference>http://arXiv.org/abs/1002.0621</cal:publicationReference>

  <cal:collaborations>
    <cal:collaboration id="c1">
      <foaf:name>ATLANTIS</foaf:name>
      <cal:experimentNumber>CERN-LHC-ATLANTIS</cal:experimentNumber>
    </cal:collaboration>
  </cal:collaborations>
  
  <cal:organizations>
    <foaf:Organization id="a1">
      <cal:orgDomain>http://yerphi.am</cal:orgDomain>
      <foaf:name>Yerevan Phys. Inst.</foaf:name>
      <cal:orgName source="INSPIRE">Yerevan Phys. Inst.</cal:orgName>
      <cal:orgStatus collaborationid="c1">Member</cal:orgStatus>
      <cal:orgAddress>Yerevan Physics Institute, Yerevan, Armenia</cal:orgAddress>
    </foaf:Organization>
    <foaf:Organization id="a59">
      <foaf:name>Florence</foaf:name>
      <cal:orgStatus>Member</cal:orgStatus>
      <cal:orgAddress>Firenze, Italy</cal:orgAddress>
    </foaf:Organization>
    <foaf:Organization id="a59a">
      <cal:orgDomain>http://fi.infn.it</cal:orgDomain>
      <foaf:name>INFN, Florence</foaf:name>
      <cal:orgName source="INSPIRE">INFN, Florence</cal:orgName>
      <cal:orgStatus>Member</cal:orgStatus>
      <cal:orgAddress>INFN Sezione di Firenze, Firenze, Italy</cal:orgAddress>
      <cal:group with="a59" />
    </foaf:Organization>
    <foaf:Organization id="a59b">
      <cal:orgDomain>http://unifi.it</cal:orgDomain>
      <foaf:name>Florence U.</foaf:name>
      <cal:orgName source="INSPIRE">Florence U.</cal:orgName>
      <cal:orgStatus collaborationid="c1">Member</cal:orgStatus>
      <cal:orgAddress>Università di Firenze, Firenze, Italy</cal:orgAddress>
      <cal:group with="a59" />
    </foaf:Organization>
    <foaf:Organization id="a109">
      <cal:orgDomain>http://cern.ch</cal:orgDomain>
      <foaf:name>CERN</foaf:name>
      <cal:orgName source="INSPIRE">CERN</cal:orgName>
      <cal:orgStatus collaborationid="c1">Member</cal:orgStatus>
      <cal:orgAddress>CERN, European Organization for Nuclear Research, Geneva, Switzerland</cal:orgAddress>
    </foaf:Organization>
  </cal:organizations>
  
  <cal:authors>
    <foaf:Person>
      <foaf:name>Vardan Khachatryan</foaf:name>
      <cal:authorNameNative>Վարդան Խաչատրյան</cal:authorNameNative>
      <foaf:givenName>Vardan</foaf:givenName>
      <foaf:familyName>Khachatryan</foaf:familyName>
      <cal:authorSuffix/>
      <cal:authorStatus/>
      <cal:authorNamePaper>V. Khachatryan</cal:authorNamePaper>
      <cal:authorNamePaperGiven>V.</cal:authorNamePaperGiven>
      <cal:authorNamePaperFamily>Khachatryan</cal:authorNamePaperFamily>
      <cal:authorCollaboration collaborationid="c1" position="Contact Person" />
      <cal:authorAffiliations>
        <cal:authorAffiliation organizationid="a1"/>
      </cal:authorAffiliations>
      <cal:authorids>
        <cal:authorid source="INSPIRE">INSPIRE-00314584</cal:authorid>
        <cal:authorid source="INTERNAL">419</cal:authorid>
      </cal:authorids>
    </foaf:Person>
    <foaf:Person>
      <foaf:name>Marcello Abbrescia</foaf:name>
      <cal:authorNameNative/>
      <foaf:givenName>Marcello</foaf:givenName>
      <foaf:familyName>Abbrescia</foaf:familyName>
      <cal:authorSuffix/>
      <cal:authorStatus/>
      <cal:authorNamePaper>M. Abbrescia</cal:authorNamePaper>
      <cal:authorNamePaperGiven>M.</cal:authorNamePaperGiven>
      <cal:authorNamePaperFamily>Abbrescia</cal:authorNamePaperFamily>
	  <cal:authorCollaboration collaborationid="c1" />
      <cal:authorAffiliations>
        <cal:authorAffiliation organizationid="a59a"/>
        <cal:authorAffiliation organizationid="a59b"/>
        <cal:authorAffiliation organizationid="a109" connection="Also at"/>
      </cal:authorAffiliations>
      <cal:authorids>
        <cal:authorid source="INSPIRE">INSPIRE-00307514</cal:authorid>
      </cal:authorids>
    </foaf:Person>
    <foaf:Person>
      <foaf:name>Benjamin C. Shen</foaf:name>
      <cal:authorNameNative/>
      <foaf:givenName>Benjamin C.</foaf:givenName>
      <foaf:familyName>Shen</foaf:familyName>
      <cal:authorSuffix/>
      <cal:authorStatus>Deceased</cal:authorStatus>
      <cal:authorNamePaper>B.C. Shen</cal:authorNamePaper>
      <cal:authorNamePaperGiven>B.C.</cal:authorNamePaperGiven>
      <cal:authorNamePaperFamily>Shen</cal:authorNamePaperFamily>
	  <cal:authorCollaboration collaborationid="c1" />
      <cal:authorAffiliations>
        <cal:authorAffiliation organizationid="a109"/>
      </cal:authorAffiliations>
      <cal:authorids>
        <cal:authorid source="INSPIRE">INSPIRE-00125803</cal:authorid>
      </cal:authorids>
    </foaf:Person>
  </cal:authors>
</collaborationauthorlist>

=== inspirehep/author.xml/example-files/example_institutional_groups.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE collaborationauthorlist SYSTEM "author.dtd">
<!-- 
	Filename: example_institutional_groups.xml.
        Example of an authors.xml file holding groups of collaborations and institutions.
!-->
<collaborationauthorlist
    xmlns:foaf="http://xmlns.com/foaf/0.1/"
    xmlns:cal="http://inspirehep.net/info/HepNames/tools/authors_xml/">
   
    <cal:creationDate>2011-02-04</cal:creationDate>
    <cal:publicationReference>CERN-2011-002</cal:publicationReference>
    <cal:collaborations>
        <cal:collaboration id="c">
            <foaf:name>ATLAS-DINGSDA-Collaboration</foaf:name>
        </cal:collaboration>
        <cal:collaboration id="c1">
            <foaf:name>ATLANTIS</foaf:name>
            <cal:experimentNumber>CERN-VLHC-ATLANTIS</cal:experimentNumber>
            <cal:group with="c" />
        </cal:collaboration>
        <cal:collaboration id="c2">
            <foaf:name>DINGSDA</foaf:name>
            <cal:experimentNumber>DESY-DINGSDA</cal:experimentNumber>
            <cal:group with="c" />
        </cal:collaboration>
    </cal:collaborations>


    <cal:organizations>
        <foaf:Organization id="a1">
            <foaf:name>Pisa</foaf:name>
            <cal:orgAddress>I-56127 Pisa, Italy</cal:orgAddress>
        </foaf:Organization>
        <foaf:Organization id="a1aa">
            <cal:orgDomain>http://www.pi.infn.it</cal:orgDomain>
            <foaf:name>Istituto Nazionale di Fisica Nucleare Pisa</foaf:name>
            <cal:orgName source="INSPIRE">INFN, Pisa</cal:orgName>
            <cal:orgName source="ROR">https://ror.org/05symbg58</cal:orgName>
            <cal:orgStatus collaborationid="c1"></cal:orgStatus>
            <cal:orgAddress>I-56127 Pisa, Italy</cal:orgAddress>
            <cal:group with="a1" />
        </foaf:Organization>
        <foaf:Organization id="a1bb">
            <cal:orgDomain>http://www.df.unipi.it</cal:orgDomain>
            <foaf:name>University of Pisa</foaf:name>
            <cal:orgName source="INSPIRE">Pisa U.</cal:orgName>
            <cal:orgName source="ROR">https://ror.org/03ad39j10</cal:orgName>
            <cal:orgStatus collaborationid="c1"></cal:orgStatus>
            <cal:orgAddress>I-56127 Pisa, Italy</cal:orgAddress>
            <cal:group with="a1" />
        </foaf:Organization>
        <foaf:Organization id="a1cc">
            <cal:orgDomain>http://www.sns.it</cal:orgDomain>
            <foaf:name>Scuola Normale Superiore</foaf:name>
            <cal:orgName source="INSPIRE">Pisa, Scuola Normale Superiore</cal:orgName>
            <cal:orgName source="ROR">https://ror.org/03aydme10</cal:orgName>
            <cal:orgStatus collaborationid="c1"></cal:orgStatus>
            <cal:orgAddress>I-56127 Pisa, Italy</cal:orgAddress>
            <cal:group with="a1" />
        </foaf:Organization>
        <foaf:Organization id="aCanada">
            <foaf:name>Canada</foaf:name>
        </foaf:Organization>
        <foaf:Organization id="a2">
            <cal:orgDomain>http://www.alberta.ca</cal:orgDomain>
            <foaf:name>University of Alberta</foaf:name>
            <cal:orgName source="ROR">https://ror.org/0160cpw27</cal:orgName>
            <cal:orgStatus collaborationid="c1"></cal:orgStatus>
            <cal:orgAddress></cal:orgAddress>
            <cal:group with="aCanada" />
        </foaf:Organization>
        <foaf:Organization id="a3">
            <cal:orgDomain>http://www.ubc.ca</cal:orgDomain>
            <foaf:name>University of British Columbia</foaf:name>
            <cal:orgName source="ROR">https://ror.org/03rmrcq20</cal:orgName>
            <cal:orgStatus collaborationid="c1"></cal:orgStatus>
            <cal:orgAddress></cal:orgAddress>
            <cal:group with="aCanada" />
        </foaf:Organization>
        <foaf:Organization id="a4">
            <cal:orgDomain>http://www.cern.ch</cal:orgDomain>
            <foaf:name>CERN</foaf:name>
            <cal:orgName source="ROR">https://ror.org/01ggx4157</cal:orgName>
            <cal:orgStatus collaborationid="c1"></cal:orgStatus>
            <cal:orgAddress></cal:orgAddress>
        </foaf:Organization>

    </cal:organizations>
   
    <cal:authors>
        <foaf:Person>
            <foaf:name>John Q. Public</foaf:name>
            <cal:authorNameNative></cal:authorNameNative>
            <foaf:givenName>John Quentin</foaf:givenName>
            <foaf:familyName>Public</foaf:familyName>
            <cal:authorSuffix></cal:authorSuffix>
            <cal:authorStatus></cal:authorStatus>
            <cal:authorNamePaper>J. Public</cal:authorNamePaper>
            <cal:authorNamePaperGiven>J.</cal:authorNamePaperGiven>
            <cal:authorNamePaperFamily>Public</cal:authorNamePaperFamily>
            <cal:authorCollaboration collaborationid="c" position="spokesperson" />
            <cal:authorAffiliations>
                <cal:authorAffiliation organizationid="aCanada" connection="" />
            </cal:authorAffiliations>
            <cal:authorids>
                <cal:authorid source=""></cal:authorid>
            </cal:authorids>
            <cal:authorFunding>Gretzky Foundation Fellow</cal:authorFunding>
        </foaf:Person>
        <foaf:Person>
            <foaf:name>Maria Rossi</foaf:name>
            <cal:authorNameNative></cal:authorNameNative>
            <foaf:givenName>Maria</foaf:givenName>
            <foaf:familyName>Rossi</foaf:familyName>
            <cal:authorSuffix></cal:authorSuffix>
            <cal:authorStatus></cal:authorStatus>
            <cal:authorNamePaper>M. Rossi</cal:authorNamePaper>
            <cal:authorNamePaperGiven>M.</cal:authorNamePaperGiven>
            <cal:authorNamePaperFamily>Rossi</cal:authorNamePaperFamily>
            <cal:authorCollaboration collaborationid="c" position="spokesperson" />
            <cal:authorAffiliations>
                <cal:authorAffiliation organizationid="a1aa" connection="" />
                <cal:authorAffiliation organizationid="a1cc" connection="" />
            </cal:authorAffiliations>
            <cal:authorids>
                <cal:authorid source=""></cal:authorid>
            </cal:authorids>
        </foaf:Person>

    </cal:authors>
</collaborationauthorlist>

=== inspirehep/author.xml/example-files/example_minimal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE collaborationauthorlist SYSTEM "author.dtd">
<!-- 
	Filename: example_minimal.xml. Example of a minimal authors.xml file.
	It includes examples for people with and without affiliations and/or author IDs
!-->
<collaborationauthorlist 
    xmlns:foaf="http://xmlns.com/foaf/0.1/" 
    xmlns:cal="http://inspirehep.net/info/HepNames/tools/authors_xml/">
  
    <cal:creationDate>2010-05-12_10:10</cal:creationDate>
    <cal:publicationReference>http://arXiv.org/abs/1002.0621</cal:publicationReference>
  
    <cal:collaborations>
        <cal:collaboration id="c1">
            <foaf:name>ATLANTIS</foaf:name>
        </cal:collaboration>
    </cal:collaborations>
  
    <cal:organizations>
        <foaf:Organization id="a1">
            <foaf:name>Yerevan Phys. Inst.</foaf:name>
            <cal:orgName source="ROR">https://ror.org/00ad27c73</cal:orgName>
        </foaf:Organization>
        <foaf:Organization id="a59a">
            <foaf:name>INFN, Florence</foaf:name>
            <cal:orgName source="ROR">https://ror.org/005ta0471</cal:orgName>
        </foaf:Organization>
        <foaf:Organization id="a59b">
            <foaf:name>Florence U.</foaf:name>
            <cal:orgName source="ROR">https://ror.org/04jr1s763</cal:orgName>
        </foaf:Organization>
        <foaf:Organization id="a109">
            <foaf:name>CERN</foaf:name>
            <cal:orgName source="ROR">https://ror.org/01ggx4157</cal:orgName>
        </foaf:Organization>
    </cal:organizations>
  
    <cal:authors>
        <!-- Author with 1 affiliation and 1 INSPIRE author ID !-->
        <foaf:Person>
            <foaf:name>Vardan Khachatryan</foaf:name>
            <foaf:givenName>Vardan</foaf:givenName>
            <foaf:familyName>Khachatryan</foaf:familyName>
            <cal:authorNamePaper>V. Khachatryan</cal:authorNamePaper>
            <cal:authorNamePaperGiven>V.</cal:authorNamePaperGiven>
            <cal:authorNamePaperFamily>Khachatryan</cal:authorNamePaperFamily>
            <cal:authorCollaboration collaborationid="c1"/>
            <cal:authorAffiliations>
                <cal:authorAffiliation organizationid="a1"/>
            </cal:authorAffiliations>
            <cal:authorids>
                <cal:authorid source="INSPIRE">INSPIRE-00314584</cal:authorid>
            </cal:authorids>
        </foaf:Person>
        <!-- Author with no affiliation and 1 internal author ID !-->
        <foaf:Person>
            <foaf:name>Marcello Abbrescia</foaf:name>
            <foaf:givenName>Marcello</foaf:givenName>
            <foaf:familyName>Abbrescia</foaf:familyName>
            <cal:authorNamePaper>M. Abbrescia</cal:authorNamePaper>
            <cal:authorNamePaperGiven>M.</cal:authorNamePaperGiven>
            <cal:authorNamePaperFamily>Abbrescia</cal:authorNamePaperFamily>
            <cal:authorCollaboration collaborationid="c1"/>
            <cal:authorids>
                <cal:authorid source="INTERNAL">514</cal:authorid>
            </cal:authorids>
        </foaf:Person>
        <!-- Author with 1 affiliation and no author ID !-->
        <foaf:Person>
            <foaf:name>Benjamin C. Shen</foaf:name>
            <foaf:givenName>Benjamin C.</foaf:givenName>
            <foaf:familyName>Shen</foaf:familyName>
            <cal:authorStatus>Deceased</cal:authorStatus>
            <cal:authorNamePaper>B.C. Shen</cal:authorNamePaper>
            <cal:authorNamePaperGiven>B.C.</cal:authorNamePaperGiven>
            <cal:authorNamePaperFamily>Shen</cal:authorNamePaperFamily>
            <cal:authorCollaboration collaborationid="c1"/>
            <cal:authorAffiliations>
                <cal:authorAffiliation organizationid="a109"/>
            </cal:authorAffiliations>
        </foaf:Person>
    </cal:authors>
</collaborationauthorlist>

=== inspirehep/author.xml/example-files/author.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE collaborationauthorlist SYSTEM "author.dtd">
<collaborationauthorlist xmlns:foaf="http://xmlns.com/foaf/0.1/"
                         xmlns:cal="http://inspirehep.net/info/HepNames/tools/authors_xml/">
	<cal:creationDate/>
	<cal:publicationReference/>
	<cal:collaborations>
		<cal:collaboration id="c1">
			<foaf:name/>
			<cal:experimentNumber/>
		</cal:collaboration>
	</cal:collaborations>
	<cal:organizations>
		<foaf:Organization id="a1">
			<cal:orgDomain>http://</cal:orgDomain>
			<foaf:name source=""/>
			<cal:orgName source=""/>
			<cal:orgStatus collaborationid="c1"/>
			<cal:orgAddress/>
			<cal:group with=""/>
		</foaf:Organization>
	</cal:organizations>
	<cal:authors>
		<foaf:Person>
			<foaf:name/>
			<foaf:givenName/>
			<foaf:familyName/>
			<cal:authorNameNative/>
			<cal:authorSuffix/>
			<cal:authorStatus/>
			<cal:authorNamePaper/>
			<cal:authorNamePaperGiven/>
			<cal:authorNamePaperFamily/>
			<cal:authorCollaboration collaborationid="c1"
			                         position=""/>
			<cal:authorAffiliations>
				<cal:authorAffiliation organizationid="a1"
				                       connection=""/>
			</cal:authorAffiliations>
			<cal:authorids>
				<cal:authorid source=""/>
			</cal:authorids>
		</foaf:Person>
	</cal:authors>
</collaborationauthorlist>
